models:
  - type: main
    engine: openai
    model: llama-3.1-8b-instant
    api_key_env_var: GROQ_API_KEY



rails:
  dialog:
    user_messages:
      embeddings_only: true
      embeddings_only_similarity_threshold: 0.50
      embeddings_only_fallback_intent: unrecognized_intent
      

enable_multi_step_generation: false

  # - type: self_check
  #   engine: openai
  #   model: gpt-4o-mini
  #   api_key_env_var: OPENAI_API_KEY

    